apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: busybox
      image: busybox
      command:
        - /bin/sh
        - -c
        - "echo 'Persistent Data' > /data/file.txt && sleep 3600"
      volumeMounts:
        - name: storage-volume
          mountPath: /data
